### ISSUE TITLE
[New WTFBin]: Skype

### ISSUE THREAD

**Issue by ghost** [mttaggart/wtfbins#1]
* **g1ng3rr00t:**
* **Skype.exe**
* **It runs whoami because it's lost**
* **https://answers.microsoft.com/en-us/skype/forum/all/skype-issues-after-update-from-82x-to-830/39b7f81a-2a97-4f0f-ac59-1cea5e5fc279**

**Comment by mttaggart** [comment]
Added in d7234a3c9eb88c03f27705599980aae54b9b1875
