### ISSUE TITLE
Squirrel.exe: (MS Teams)

### ISSUE THREAD

**Issue by SpikeRoche** [mttaggart/wtfbins#10]
* **Contributor Name: SpikeRoche**
* **Application/Executable: Microsoft Teams/Squirrel.exe**
* **WTF Behavior Description: A process called Squirrel.exe. **
* **Link to Documentation of Behavior: https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/include-exclude-teams-from-antivirus-dlp**

**Comment by mttaggart** [comment]
Thanks, this is really cool! 

Does `squirrel.exe` do anything particularly strange? Or is the WTF coming from the mere existence of an executable named "squirrel?"

**Comment by SpikeRoche** [comment]
It can be used as a lolbin and shows up a lot when folks first start logging Windows or analyzing logs.

**Comment by mttaggart** [comment]
@SpikeRoche I need a little more info to qualify this as a WTFBin. Does `squirrel.exe` do anything strange, or is it just the name? I'm looking for a reason why this would appear malicious during threat hunting or incident response.

**Comment by SpikeRoche** [comment]
It makes outbound connections, creates a file/process called Update.exe,
and loads multiple dll's.
[image: chrome_rTX3g6Qecp.png]
[image: chrome_GTt5SGqXYp.png][image: chrome_S8pHssV7fm.png]

**Comment by mttaggart** [comment]
Sorry, I can't see those images. But creating a new process and loading DLLs is normal behavior for any Windows executable. I think for now, we're going to close this one until we have some evidence that is a bit more suspicious. I know it's on the Teams exclusions list, but we don't know _why_. That's what we'd need.
