### ISSUE TITLE
Cisco AnyConnect: Diagnose Connection Issues, WHOAMI as system

### ISSUE THREAD

**Issue by no2aq** [mttaggart/wtfbins#12]
* **Contributor Name: no2aq
* **Application/Executable: Cisco AnyConnect
* **WTF Behavior Description: If an end user runs Diagnostics from the Cisco AnyConnect agent, this will run WHOAMI as System. 
* **Link to Documentation of Behavior:**

c:\program files (x86)\cisco\cisco anyconnect secure mobility client\opswat\wadiagnose.exe is the parent process that calls it. 

Only seen if running Sysmon. 

Tested on Cisco AnyConnect Agent v.4.9.06037

**Comment by mttaggart** [comment]
@no2aq,

Thank you for this submission! It seems promising. But in order to be approved, we do need a link to documentation of the behavior. If no official documentation exists, this is your chance to do a writeup showing the WTFBin in action! Once completed, link it here and we'll move forward.
