### ISSUE TITLE
[DameWare Mini Control]: DameWare.exe

### ISSUE THREAD

**Issue by tallcyberguy** [mttaggart/wtfbins#13]
* **Huseyin EKSI:**
* **DameWare Mini Control.exe:**
* **This little guy might look like scanning or making connections to different IPs in your network(which creates more alerts), add to your exception list. It's a remote control software a little bit different than our beloved RDP.:**
* **https://www.dameware.com/dameware-mini-remote-control:**

**Comment by mttaggart** [comment]
@tallcyberguy Thank you for your submission!

The link you provided is just for the product page. Is there official documentation of this behavior? If not, we ask that you publish a writeup (or find one that exists) and provide that to support the evidence for the WTFBin.

**Comment by tallcyberguy** [comment]
I actually came across this at work. Some security products raise an alert. I will look into that when possible
