### ISSUE TITLE
[New WTFBin]: Silver Bullet Technology's Ranger runs a Bloodhound.exe

### ISSUE THREAD

**Issue by Purp1eW0lf** [mttaggart/wtfbins#14]
* **Contributor Name:** Dray Agha [@purp1ew0lf](https://twitter.com/purp1ew0lf)
* **Application/Executable:** Bloodhound.exe (C:\Program Files (x86)\Silver Bullet Technology\Ranger\Logging\Bloodhound.exe)
* **WTF Behavior Description:** Silver Bullet Technology's Ranger runs an executable called Bloodhound.exe. It doesn't appear to be SpecterOps's Bloodhound tool for Active Directory mapping, it merely shares a namesake. 
* **Link to Documentation of Behavior:** Referenced [here](https://sbullet.com/products/ranger-2/ranger-tools/) and [here](https://www.advanceduninstaller.com/Ranger-c188e76ee3c20823ed77b82c65bce7bc-application.htm) 

<img width="342" alt="image" src="https://user-images.githubusercontent.com/44196051/159670129-8dd8eb03-3388-493f-bff3-e483a227c10f.png">

![image](https://user-images.githubusercontent.com/44196051/159670534-67407793-0f71-4637-950c-f71bca53db47.png)

**Comment by HuskyHacks** [comment]
cracking up over here

**Comment by Purp1eW0lf** [comment]
Couldn’t make it up 😂😒

**Comment by mttaggart** [comment]
Absolute banger. Added in 4b5b25e56c71c539dec1dbdbc3bab2c769075f31.
