### ISSUE TITLE
[New WTFBin]: WTFBIN Here

### ISSUE THREAD

**Issue by MATTANDERS0N** [mttaggart/wtfbins#16]
* **Contributor Name:** Matt Anderson
* **Application/Executable:**  c:\windows\system\svchost.exe, c:\windows\system\spoolsv.exe, c:\windows\system\explorer.exe
* **WTF Behavior Description:**.  Named after legitimate Windows binaries, in the wrong location.  They were spawned in succession from C:\Program Files (x86)\noregon\JPRO diagnostics\Fleets.exe" > "C:\Program Files (x86)\noregon\JPRO diagnostics\_jpro_start.exe" > C:\Users<user>\AppData\Local\icsys.icn.exe" > c:\windows\system\explorer.exe >  c:\windows\system\spoolsv.exe > c:\windows\system\svhost.exe.   The files are custom binaries compiled with Visual Basic.  They appear to be changed/created regularly as the hashes seem to change often. 
* **Link to Documentation of Behavior:**. Noregon support said they were a part of the software but had no official documentation to provide me.   https://shop.noregon.com/collections/jpro-professional
* **Please provide any images for additional evidence.**
![image](https://user-images.githubusercontent.com/75185144/160493606-185e1e80-77d9-48d5-bf5e-536a6e282201.png)
![image](https://user-images.githubusercontent.com/75185144/160494228-b633f757-49bf-4a24-87e6-a2137e7c9fbd.png)

**Comment by mttaggart** [comment]
Added in 3723640dcd3488496b4e63b9645fc4bd7c083c81.
