### ISSUE TITLE
[New WTFBin]: AGMServive.exe LSASS read

### ISSUE THREAD

**Issue by ghost** [mttaggart/wtfbins#17]
g1ng3rr00t

AGMService.exe / Adobe Genuine Monitor Service

AGMService.exe opens and reads from the LSASS process

I was unable to find much information about this issue specifically (although I did not contact Adobe at all) aside from this forum post from 2019 https://community.adobe.com/t5/acrobat-discussions/credential-theft-adobe-genuine-software-service-agmservice-exe/td-p/10745517, and it being excluded in Olaf Hartong's sysmon modular configuration repository (https://github.com/olafhartong/sysmon-modular/blob/master/sysmonconfig-excludes-only.xml).

![agmservice](https://user-images.githubusercontent.com/89753991/160697982-26257d08-69fd-41c7-bdb7-0c488697fe61.png)
![Unknown](https://user-images.githubusercontent.com/89753991/160697979-7c579248-a718-4a64-8936-b18384612789.png)
![Unknown-2](https://user-images.githubusercontent.com/89753991/160697975-5fa4bb7d-0c7d-4c1f-9064-eb151e770ec9.png)

**Comment by mttaggart** [comment]
Added in e8acedb.
