### ISSUE TITLE
Powershell_ise.exe

### ISSUE THREAD

**Issue by dakkmaddy** [mttaggart/wtfbins#18]
* **Contributor Name:** jmm
* **Application/Executable:** powershell_ise.exe
* **WTF Behavior Description:** Only humans launch integrated scripting engine.
* **Link to Documentation of Behavior:** N/A
![psise](https://user-images.githubusercontent.com/42662940/160922160-4d4dd954-c192-4ada-87db-655b835ae5ca.png)

* **Please provide any images for additional evidence.**

**Comment by mttaggart** [comment]
Hey @dakkmaddy, thank you for the submission! 

A user running `powershell_ise.exe` is a legitimate action to alert on, as it could indicate suspicious behavior. That's different than a benign application _appearing_ malicious based on its own behaviors. I'd check some of the other WTFBin accepted submissions for examples of these. But for now, I'm going to close this one out.
