### ISSUE TITLE
[New WTFBin]: WTFBIN Here

### ISSUE THREAD

**Issue by dakinedakine99** [mttaggart/wtfbins#20]
* **Contributor Name:**
Bumbucha
* **Application/Executable:**
SenseNdr.exe
* **WTF Behavior Description:**
 Totally normal command of 4000 characters in base64. Only legitimate use of this much base64 in history.
* **Link to Documentation of Behavior:**
[Documentation](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-discovery?view=o365-worldwide)
* **Please provide any images for additional evidence.**
![wtf](https://user-images.githubusercontent.com/100836936/163134741-8cde713a-292d-4a8a-a412-eecb5d068883.png)

**Comment by mttaggart** [comment]
@dakinedakine99, thank you for the submission!

Before approval, I need a little more info about this! Many other components of Windows management actually use base64 Powershell encoding (one of them is already a WTFbin!). Please decode one of these commands and provide that screenshot as well to indicate what this executable is really doing.

**Comment by dakinedakine99** [comment]
Don't want to include the entire command since it includes network info, but mainly regexes related to network vulnerabilities. I assume this is for transparency. masquerading potential imo. 
![wtfbin](https://user-images.githubusercontent.com/100836936/165029493-65ea645e-91c0-4e4c-8f50-4f1c7818a64a.jpg)

**Comment by dakinedakine99** [comment]
sensendr.exe "*encoded text*", there's no decode, so not that big of a deal, but still, wtf.

**Comment by mttaggart** [comment]
Added in c2fb3fc4da2041d2b2d867170da3a51363903490

**Comment by chiwawa969** [comment]
@dakinedakine99 What base64 is used for the sensendr.exe ? Tried a whole bunch of formats UTF-8, UTF-16 with Cyberchef but cannot decrypt. I see from your screenshot you are using Cyberchef, can you give me the recipe please? Thanks

**Comment by Ragex0** [comment]
This is what I used

![cyberchef_recipe](https://github.com/mttaggart/wtfbins/assets/146101113/c4979839-3f36-4918-b407-2b937735ac72)
