### ISSUE TITLE
[New WTFBin]: WTFBIN bdbicextractor.exe

### ISSUE THREAD

**Issue by redblueops** [mttaggart/wtfbins#21]
* **Contributor Name: Alexandros Pappas
* **Application/Executable: bradbury.invcol.9.5.2.1.dll; dsapi.exe; and bdbicextractor.exe
* **WTF Behavior Description: Three files (bradbury.invcol.9.5.2.1.dll; dsapi.exe; and bdbicextractor.exe) triggered an AV alert due to incorrect file attributes; they are not malicious. Files were shipped with incorrect file attributes. 
* **Link to Documentation of Behavior: https://community.carbonblack.com/t5/Knowledge-Base/Carbon-Black-Cloud-Console-Dell-Software-Update-False-Positive/ta-p/102900
* https://www.dell.com/support/kbdoc/en-au/000185741/dell-client-updates-launched-on-april-22-2021-incorrectly-identified-as-malware
* **Please provide any images for additional evidence.**

**Comment by mttaggart** [comment]
@redblueops, thank you for your submission!

Although this is a false positive, these files don't really meet the criteria of a WTFBin. These are mistaken file attributes, but not suspicious _behaviors_ of the executables. For that reason, I'm gonna close this out for now.
