### ISSUE TITLE
[New WTFBin]: ArcGIS deploys whoami.exe

### ISSUE THREAD

**Issue by Purp1eW0lf** [mttaggart/wtfbins#28]
* **Contributor Name:** Dray Agha [@Purp1eW0lf](https://twitter.com/Purp1eW0lf)
* **Application/Executable:** ArcGIS, specifically two binaries: `C:\Program Files\ArcGIS\Portal\framework\runtime\jre\bin\javaw.exe` and` C:\Program Files\ArcGIS\Portal\framework\service\bin\ArcGISPortal.exe`
* **WTF Behavior Description:** ArcGIS runs whoami.exe 
* **Link to Documentation of Behavior:** Apparently, ArcGIS is checking the appropriate user who "can read / write to the required directories" [[1]](https://community.esri.com/t5/arcgis-enterprise-portal-questions/arcgis-portal-quot-whoami-exe-quot/td-p/1174531)
* **Please provide any images for additional evidence.** 
I know other Defenders have been caught out by this weird activity [[2](https://twitter.com/MikeDaniels00/status/1407383747985653769)]. But, ArcGIS spawning whoami is completely legitimate and authorised activity.  Huntress telemetry shows ~60,000 in the last 15 hours. I would advice adding this very specific activity to an ignore list, so it does not trigger a detection. 

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/44196051/190622843-c9a71b04-492f-4634-9ecc-5cae6e04fd06.png">

**Comment by mttaggart** [comment]
Added in 408c01d665d8cd123d3d589ea3fb647247994de6. Thanks as always bud!
