### ISSUE TITLE
[New WTFBin]: Nim language install binaries

### ISSUE THREAD

**Issue by HuskyHacks** [mttaggart/wtfbins#3]
* **Contributor Name:** HuskyHacks
* **Application/Executable:** Nim language install binaries
* **WTF Behavior Description:** The Nim language install binaries in certain versions trigger Windows Defender. These include nimble.exe, finish.exe, koch.exe, and other binaries that come packaged during a stock install of Nim.
* **Link to Documentation of Behavior:** 
  * https://github.com/HuskyHacks/the-crown-defcon615/blob/main/notebooks/NimbleAVExcursion.ipynb
  *  https://youtu.be/suKfsnOa_OU?t=570
  * https://github.com/nim-lang/Nim/issues/17820

**Comment by mttaggart** [comment]
Added with 7be027e8e0c186bcb35f0e4fc43b42b969a5ac8b
