### ISSUE TITLE
[New WTFBin]: WTFBIN Here

### ISSUE THREAD

**Issue by artifex333** [mttaggart/wtfbins#30]
* **Contributor Name: Michael Weber "mthrfcknruckus" @mjweber915**
* **Application/Executable: spaceman.exe**
* **WTF Behavior Description: The file is associated with EaseUS Partition Manager or Hard Drive Tools 2003 by TradeTouch.com. Aside from the odd name of the binary, other WTF behaviors include installing to system32 and creating scheduled tasks. These stand out when triaging in PowerShell using `Get-ScheduledTask | Select -Property Author`.**
* **Link to Documentation of Behavior: https://answers.microsoft.com/en-us/windows/forum/all/windows-10-spacemanexe/c60c4d6b-0bca-49e3-8054-68213efbd67a**
* **Please provide any images for additional evidence. https://github.com/mthrfcknruckus/spaceman.exe/blob/main/2022-10-07%2015_36_49-Administrator_%20Windows%20PowerShell.png**

**Comment by mttaggart** [comment]
The image link appears broken. Could we get another one please, especially one that includes the scheduled tasks?

**Comment by artifex333** [comment]
sorry for the confusion, see below for results of commands schtasks /query /v /fo LIST | findstr /c:"spaceman.exe" | findstr /v /c:"Task To Run" and Get-ScheduledTask | Select -Property Author (spaceman.exe task is highlighted):

![image](https://user-images.githubusercontent.com/99111739/200188949-4c2e29e2-9a29-4603-ae4d-d0bf59dbf5ee.png)

![2022-11-06 10_18_02-Window](https://user-images.githubusercontent.com/99111739/200188052-b3dff4a8-892e-4cea-929f-9044793e6554.png)

**Comment by mttaggart** [comment]
Added in 4cd8129f950d65bcc752bca156dc54402ddca503
