### ISSUE TITLE
[New WTFBin]: SCS' PowerView.exe triggers PowerSploit's detection

### ISSUE THREAD

**Issue by Purp1eW0lf** [mttaggart/wtfbins#31]
* **Contributor Name:** Dray Agha [@Purp1eW0lf](https://twitter.com/Purp1eW0lf)
* **Application/Executable:** PowerView.exe , known paths so far are `C:\SCS\Powerview\Powerview.exe` or `C:\Program Files (x86)\SCS\PowerView\PowerView.exe` 
* **WTF Behavior Description:** May trip detectors for the [PowerShell-based Active Directory enumeration tool of the same name](https://powersploit.readthedocs.io/en/latest/Recon/)
* **Link to Documentation of Behavior:** "PowerView is a program used to control various equipment built by Specialty Coating Systems" [[1]](https://scscoatings.com/equipment/ionic-contamination-test/ionograph-smd-v/). Just a harmless program for controlling operational technology, but similarly named to an offensive security tool you'd rather not see in your domain, unauthorised. 
* **Please provide any images for additional evidence.** 
Huntress telemetry shows 2 hits in the last 24 hours, so this is a _very_ obscure WTFBin. I would advice adding this very specific activity to an ignore list if SCS' PowerView exists in your telemetry, so it does not trigger a detection. 

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/44196051/200796447-e6925bed-4d87-48a0-8075-34ae0639876d.png">

<img width="844" alt="image" src="https://user-images.githubusercontent.com/44196051/200796605-2d3b1c63-feca-4654-9338-21f3d34b6db8.png">

<img width="996" alt="image" src="https://user-images.githubusercontent.com/44196051/200796835-0622fbe7-dbd6-4fa9-8a5e-b3e723aed781.png">

**Comment by mttaggart** [comment]
Hey @Purp1eW0lf , sorry I'm just getting to this. I am not sure I'd classify this as a WTFBin. Here's why: `PowerView.exe` is not itself performing anything particularly odd or suspicious. What we have here is a classic false positive on the part of our detection tools. I'll grant it's a weird name, but for me it doesn't quite meet the shape of the WTFBins we've listed.

**Comment by Purp1eW0lf** [comment]
Absolutely, NP 😎
