### ISSUE TITLE
[New WTFBin]: ESET protection suite

### ISSUE THREAD

**Issue by pspacek** [mttaggart/wtfbins#32]
* **Contributor Name:** pspacek
* **Application/Executable:** ESET Antispam, Parental Controls, LiveGrid (online reputation database)
* **WTF Behavior Description:** Various modules of ESET protection suite perform odd DNS lookups to subdomains of e5.sk domain.
* **Link to Documentation of Behavior:** https://support.eset.com/en/kb332-ports-and-addresses-required-to-use-your-eset-product-with-a-third-party-firewall

**Comment by mttaggart** [comment]
Thank you for this submission! This is a very similar behavior to a Sophos product we have! It would be amazing if you could provide log samples of the DNS queries.

**Comment by pspacek** [comment]
Okay, here is a sample from tcpdump:
```
TXT? oa5jhh3yxkgu5kpwgnjmgk54pubqeaqbaeaq.a.e.e5.sk.
TXT? wzxh7gqaszmunhqg3g5ouiiuwebqeaqbaeaq.a.e.e5.sk.
TXT? xegjkvpuklfebhejqeve4mltsmbqeaqbaeaq.a.e.e5.sk.
TXT? vscxkxbn55aelaru6a6y3dxznebqeaqbaeaq.a.e.e5.sk.
TXT? dc5wtaihc6luvphgub6laccokebqeaqbaeaq.a.e.e5.sk.
```

**Comment by mttaggart** [comment]
Added in e0d3514fcd4b3dd6f7af2c43ddb077425d41d109
