### ISSUE TITLE
[New WTFBin]: microsoft.todos.systemtrayextension.exe

### ISSUE THREAD

**Issue by redblueops** [mttaggart/wtfbins#35]
* **Contributor Name: Alexandros Pappas
* **Application/Executable: microsoft.todos.systemtrayextension.exe
* **WTF Behavior Description: The application svchost.exe -k wsappx -p -s AppXSvc dropped a known virus (Malware: APC) onto the device.
* **Link to Documentation of Behavior: https://community.carbonblack.com/t5/Knowledge-Base/All-Products-RESOLVED-Potential-False-Positive-for-microsoft/ta-p/111920, https://www.joesandbox.com/analysis/597580/0/html, https://hybrid-analysis.com/sample/04a7425a8177d9dcc428327bb1ce9409fe6510aa9dab640cd39c9c8e4a9153c8
* **Please provide any images for additional evidence: N/A

**Comment by mttaggart** [comment]
Thank you for the submission! As this was a corrected false positive and not an ongoing behavior, I'm afraid this doesn't qualify as a WTFBin.
