### ISSUE TITLE
[New WTFBin]: TrendMicro HostedAgent.exe

### ISSUE THREAD

**Issue by biffalo** [mttaggart/wtfbins#37]
* **Contributor Name: Biffalo**
* **Application/Executable: C:\Program Files (x86)\Trend Micro\Client Server Security Agent\HostedAgent\HostedAgent.exe**
* **WTF Behavior Description: Trend Micro WFBS Agent runs whoami.exe regularly as system for reasons unknown
![2023-01-25 08_13_36](https://user-images.githubusercontent.com/26933099/214572603-5691a8d4-b254-4c79-b18c-e0a59e366eff.png)
![2023-01-25 08_12_05](https://user-images.githubusercontent.com/26933099/214572609-bc35537d-0705-41d1-91a4-b96b071d713c.png)
* **Link to Documentation of Behavior: n/a**

**Comment by mttaggart** [comment]
Added in b4d480c832304f9294dea1cd5b604de640132b70
