### ISSUE TITLE
[New WTFBin]: NetBIOS over TCP

### ISSUE THREAD

**Issue by super-phreak** [mttaggart/wtfbins#4]
* Ductape and Dreams:
* NetBIOS over TCP
* Listens on random high ports and has machines all over the network connect at odd times.
* https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-NBTE/%5bMS-NBTE%5d.pdf

**Comment by mttaggart** [comment]
Completed with 0db326742d9ea11532cc8b7c763797272e89a1ef
