### ISSUE TITLE
[New WTFBin]: Guest user tries to login whenever a folder gets shared with "Everyone"

### ISSUE THREAD

**Issue by ygil1234** [mttaggart/wtfbins#40]
* **Contributor Name: ygil1234**
* **Application/Executable: Windows Explorer (explorer.exe)**
* **WTF Behavior Description: Sharing a Windows folder with "Everyone" permissions, will cause a failed logon of user Guest.**
* **Link to Documentation of Behavior: Found that behavior while investigating an incident, here is another similar case - https://learn.microsoft.com/en-us/answers/questions/224757/failed-type-3-logons-on-domain-workstation-by-gues#:~:text=4%3A56%20AM-,Hello%2C,-Thank%20you%20so**
* **Please provide any images for additional evidence. 
<img width="629" alt="image" src="https://user-images.githubusercontent.com/63286048/218282880-7ccfb007-62b9-4bb5-9491-0fe84c236818.png">
**

**Comment by mttaggart** [comment]
Thanks for your patience! Added in a5c5422
