### ISSUE TITLE
[New WTFBin]: gc_worker.exe

### ISSUE THREAD

**Issue by rcegan** [mttaggart/wtfbins#41]
* **Contributor Name:** rcegan
* **Application/Executable:** Azure Connected Machine Agent - gc_worker.exe
* **WTF Behavior Description:** Spawns a process that runs encoded Powershell strings. Triggers when the agent downloads new policies from Azure.
* **Link to Documentation of Behavior:** N/A - I can't find any resources online that mention this behaviour.
* **Please provide any images for additional evidence.**
![image](https://user-images.githubusercontent.com/5835816/219515022-a81fc349-a045-4c20-961a-0fd1f0c57437.png)

**Comment by mttaggart** [comment]
Added in 6fb27f5c72e15c6aa696b46eb00db9c55db9553d
