### ISSUE TITLE
[New WTFBin]: Nutanix Guest Tools Runs Encoded Powershell Commands

### ISSUE THREAD

**Issue by mbabinski** [mttaggart/wtfbins#46]
* **Contributor Name:**
Micah Babinski ([@micahbabinski](https://twitter.com/micahbabinski))
* **Application/Executable:**
[Nutanix Guest Tools](https://next.nutanix.com/how-it-works-22/nutanix-guest-tools-37346)
* **WTF Behavior Description:**
Nothing too exciting, just another software component that runs encoded powershell. While tuning an alert I observed two commands like: `powershell.exe -NoProfile -EncodedCommand VwByAGkAdABlA .....`. There appeared to be no logged parent process, at least in the environment where I observed it. The commands decode to:
`Get-WmiObject -Namespace root\wmi -Class MSiSCSIInitiator_SendTargetPortalClass | Foreach-Object { Write-Host $_.PortalAddress }` and `Write-Host (Get-WmiObject -Namespace root\wmi -Class MSiSCSIInitiator_MethodClass).iSCSINodeName`.
* **Link to Documentation of Behavior:**
https://www.reddit.com/r/nutanix/comments/cyvqkf/apparent_powershell_activity_on_host_vms/
[CyberChef Recipe](https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true,false)Decode_text('UTF-16LE%20(1200)')&input=UndCbEFIUUFMUUJYQUcwQWFRQlBBR0lBYWdCbEFHTUFkQUFnQUMwQVRnQmhBRzBBWlFCekFIQUFZUUJqQUdVQUlBQnlBRzhBYndCMEFGd0Fkd0J0QUdrQUlBQXRBRU1BYkFCaEFITUFjd0FnQUUwQVV3QnBBRk1BUXdCVEFFa0FTUUJ1QUdrQWRBQnBBR0VBZEFCdkFISUFYd0JUQUdVQWJnQmtBRlFBWVFCeUFHY0FaUUIwQUZBQWJ3QnlBSFFBWVFCc0FFTUFiQUJoQUhNQWN3QWdBSHdBSUFCR0FHOEFjZ0JsQUdFQVl3Qm9BQzBBVHdCaUFHb0FaUUJqQUhRQUlBQjdBQ0FBVndCeUFHa0FkQUJsQUMwQVNBQnZBSE1BZEFBZ0FDUUFYd0F1QUZBQWJ3QnlBSFFBWVFCc0FFRUFaQUJrQUhJQVpRQnpBSE1BSUFCOUFB)
* **Please provide any images for additional evidence.**
None, log screenshots available upon request!

**Comment by mttaggart** [comment]
Thanks for your patience, and the great submission as always, @mbabinski! Added in 3c70947
