### ISSUE TITLE
[New WTFBin]: Trojan.exe

### ISSUE THREAD

**Issue by mvarian** [mttaggart/wtfbins#47]
* **Contributor Name:** mvarian
* **Application/Executable:** trojan.exe
* **WTF Behavior Description:** Provider for bridging the transfer of PHI to insurance billing is provided by Trojan Services and installs trojan.exe on servers.
* **Link to Documentation of Behavior:** https://trojanonline.com
* **Please provide any images for additional evidence.**

**Comment by mttaggart** [comment]
Thanks for your patience! I'd like to see some logs of this event in action, so we can add it to the entry.

**Comment by mttaggart** [comment]
Closed for lack of evidence.
