### ISSUE TITLE
[New WTFBin]: code.exe spawn cmd.exe 

### ISSUE THREAD

**Issue by ThureinOo** [mttaggart/wtfbins#48]
* **Contributor Name:** Thurein Oo
* **Application/Executable:** code.exe (Microsoft VS Code)
* **WTF Behavior Description:** code.exe from Microsoft VS Code creates process including cmd.exe or powershell.exe when typescript codes are compiled.
* **Link to Documentation of Behavior:** https://code.visualstudio.com/docs/typescript/typescript-compiling
* **Please provide any images for additional evidence.**
![image](https://github.com/mttaggart/wtfbins/assets/47708575/b8b5b549-fcb2-4332-8112-1aab70dbf84f)
![image](https://github.com/mttaggart/wtfbins/assets/47708575/956762fd-7021-4429-af32-8de81d5b6565)

**Comment by mttaggart** [comment]
Hey @ThureinOo, thank you so much for your submission, and your patience!

Although `cmd.exe` by itself can be strange, I do not think it is unexpected for a code editor to be kicking off command prompts, especially  given the nature of many plugins. 

This submission also doesn't show that the command line params are, so there's not a lot to go on. Regardless, given the nature of VS Code, I don't know if I'm ready to call this a WTFBin. If you provide the command line and it looks particularly sus, like base64-encoded commands, we can revisit this.
