### ISSUE TITLE
[New WTFBin]: Network Detective Data Collector

### ISSUE THREAD

**Issue by Purp1eW0lf** [mttaggart/wtfbins#5]
* **Contributor Name**: Dray Agha [@purp1ew0lf](https://twitter.com/purp1ew0lf)
* **Application/Executable**: Network Detective Data Collector (nddc.exe)
* **WTF Behavior Description**: The executable for Network Detective Data Collector displays false positive activity similar to Impacket's WMI/SMBexec
* **Link to Documentation of Behavior**: It's a Rapid Fire Tools / Kaseya bit of tooling. Unfortunately I can't find specific section of [documentation ](https://www.rapidfiretools.com/nd/RapidFire_Network_Detective_User_Guide.pdf)that explains the context of this activity. 
 
![image](https://user-images.githubusercontent.com/44196051/157226071-1171bb81-b1f2-4115-9690-8b492be63cc9.png)

![image](https://user-images.githubusercontent.com/44196051/157226324-408036ed-69da-4fcd-bbcb-23b13a5a457b.png)

**Comment by mttaggart** [comment]
Thank you for the submission!

Added in 95516e5.

**Comment by HuskyHacks** [comment]
sus AF, if I saw that in my logs I'd break out the flamethrower. Great WTFBin!
