### ISSUE TITLE
[New WTFBin]: IBM Storage Insights Data Collector Runs Batch Script with WMIC Process Call Create

### ISSUE THREAD

**Issue by mbabinski** [mttaggart/wtfbins#50]
* **Contributor Name:**
Micah Babinski (@mbabinski), William Rotchford
* **Application/Executable:**
[IBM Storage Insights](https://www.ibm.com/products/storage-insights) Data Collector
* **WTF Behavior Description:**
The data collector periodically runs a command like:
`cmd.exe /c wmic process call create "C:\...\datacollectorbin\collectorSrvWatchDog.bat"`
This may trigger detection rules geared towards T1047: Windows Management Instrumentation which look for wmic.exe being used to covertly spawn processes.
* **Link to Documentation of Behavior:**
https://www.ibm.com/support/pages/carbon-black-security-alert-executing-wmicexe
* **Please provide any images for additional evidence.**
![image](https://github.com/mttaggart/wtfbins/assets/63474467/2d9f6095-c020-4f93-86ed-6f3af6246125)

**Comment by mttaggart** [comment]
Hey Micah! Always a pleasure. I'll get this added ASAP.

**Comment by mttaggart** [comment]
Added in e43b954
