### ISSUE TITLE
[New WTFBin]: Jetbrains IDE using WMI to query antivirus product

### ISSUE THREAD

**Issue by ThureinOo** [mttaggart/wtfbins#51]
* **Contributor Name:** Thurein Oo
* **Application/Executable:** idea64.exe, rider64.exe (Jetbrains)
* **WTF Behavior Description:** idea64.exe and rider64.exe from Jetbrains query the installed antivirus product in the exact same way that malicious programs do using the command:
`wmic /namespace:\\root\securitycenter2 path antivirusproduct get displayname,productstate`
* **Link to Documentation of Behavior:** 
https://rider-support.jetbrains.com/hc/en-us/community/posts/360010724079-Why-is-Rider-making-wmic-commands-to-get-AntiVirus-name- 
https://security.stackexchange.com/questions/255534/jetbrains-ide-using-wmi-to-query-antivirus-product
* **Please provide any images for additional evidence.**

**Comment by mttaggart** [comment]
This one is amazing. Thank you! I wonder what they'll do after `wmic` goes away...

**Comment by mttaggart** [comment]
Added in c064cff8
