### ISSUE TITLE
[New WTFBin]: WTFBIN Here

### ISSUE THREAD

**Issue by ThureinOo** [mttaggart/wtfbins#52]
* **Contributor Name:** Thurein Oo
* **Application/Executable:** EndpointBasecamp.exe, RiskIndexCollector.exe 
* **WTF Behavior Description:** Trend Micro EndpointBasecamp.exe drops RiskIndexCollector.exe which invoke wmic to get list of Hotfixes/Patches using the command
`wmic qfe get Description, HotfixID, InstalledOn`
* **Link to Documentation of Behavior:**
* https://any.run/report/123b7b8262d000d098c4d18bec592f22677d2374bef1e59573a05aeea9a58b3b/73ede74d-a30d-45d2-91c2-cc1870b275f6
* **Please provide any images for additional evidence.**
![image](https://github.com/mttaggart/wtfbins/assets/47708575/ea3e728d-4799-499b-8417-56cfc9b1d066)

![image](https://github.com/mttaggart/wtfbins/assets/47708575/8a919e86-00ab-40b4-aeca-a94a457be752)

**Comment by mttaggart** [comment]
Added in 229e014
