### ISSUE TITLE
[New WTFBin]: WTFBIN Here

### ISSUE THREAD

**Issue by ThureinOo** [mttaggart/wtfbins#53]
* **Contributor Name:**Thurein Oo
* **Application/Executable:** draw.io.exe
* **WTF Behavior Description:** draw.io.exe uses attrib.exe to hide the file .dtmp using the command  `attrib +h filename.dtmp`.
* **Link to Documentation of Behavior:**
* https://github.com/jgraph/drawio-desktop/issues/1194
* https://github.com/jgraph/drawio-desktop/discussions/1535
* **Please provide any images for additional evidence.**

**Comment by mttaggart** [comment]
Added in f019266. Thanks for your patience!
