### ISSUE TITLE
[New WTFBin]: ekrn.exe

### ISSUE THREAD

**Issue by redblueops** [mttaggart/wtfbins#59]
* **Contributor Name: Alexandros Pappas
* **Application/Executable: ekrn.exe (Ekrn.exe is the executable file for the ESET NOD32 Antivirus kernel)
* **WTF Behavior Description: ESET NOD32 Antivirus kernel performs Random-Looking Domain Names.
* **Link to Documentation of Behavior: N/A
<img width="576" alt="ekrn1" src="https://github.com/user-attachments/assets/c58fb677-38be-414a-af1d-2f214145f80c">
<img width="957" alt="ekrn2" src="https://github.com/user-attachments/assets/9c67febd-e799-40f2-a2e1-4ff277d4a3b1">

* **Please provide any images for additional evidence. Please see attached above.

Mitre attack
•	TA0011: The adversary is trying to communicate with compromised systems to control them. Command and Control consists of techniques that adversaries may use to communicate with systems under their control within a victim network. Adversaries commonly attempt to mimic normal, expected traffic to avoid detection. There are many ways an adversary can establish command and control with various levels of stealth depending on the victim's network structure and defenses. 
o	https://attack.mitre.org/tactics/TA0011/
•	T1568.002: Adversaries may make use of Domain Generation Algorithms (DGAs) to dynamically identify a destination domain for command and control traffic rather than relying on a list of static IP addresses or domains. This has the advantage of making it much harder for defenders to block, track, or take over the command and control channel, as there potentially could be thousands of domains that malware can check for instructions. 
o	https://attack.mitre.org/techniques/T1568/002/

**Comment by mttaggart** [comment]
Nice one! Added in e9f69b2
