### ISSUE TITLE
LogMeIn.exe (LogMeIn Product Suite)

### ISSUE THREAD

**Issue by WidespreadPandemic** [mttaggart/wtfbins#9]
* **Contributor Name: t3chn1qu3_/WSP (@t3chn1qu3_WSP)
* **Application/Executable: LogMeIn.exe
* **WTF Behavior Description: LogMeIn runs "avfilter.js" via cscript to check what AV is running on your system for some godawful reason. As far as I am aware, they have yet to provide any substantial documentation or reasoning as to why. 
* **Link to Documentation of Behavior: 
* https://community.logmein.com/t5/LogMeIn-Central-Discussions/Why-AVfilter-js-running-in-my-logMein-client-machines/td-p/255466 
* https://twitter.com/cyberkryption/status/822024889351733248

**Comment by mttaggart** [comment]
This one is glorious. Thank you for the submission! Approved and will be added ASAP!

**Comment by mttaggart** [comment]
Added in 22339fa
